import fs from 'node:fs';
import path from 'node:path';
const base='https://evsavelev.github.io/kinder-party-dom-nizhnevartovsk/';
const vk='https://vk.ru/kinderparty_nv';
const reviews='https://2gis.ru/nizhnevartovsk/firm/70000001047353725/tab/reviews';
const wa=(message='Здравствуйте! Хочу узнать свободную дату для праздника. Дата: … Возраст ребёнка: … Количество гостей: … Праздник у вас или с выездом: …')=>'https://wa.me/79825357237?text='+encodeURIComponent(message);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const media=JSON.parse(fs.readFileSync('assets/media-manifest.json','utf8'));
function img(name,alt,{hero=false,cls=''}={}){const m=media.find(x=>x.file===`assets/images/${name}.webp`);if(!m)throw Error(name);const small=fs.existsSync(`assets/images/${name}-640.webp`);return `<img class="${cls}" src="${m.file}" ${small?`srcset="assets/images/${name}-640.webp 640w, ${m.file} ${m.width}w" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 1000px) 50vw, 620px"`:''} width="${m.width}" height="${m.height}" alt="${esc(alt)}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;}
const arrow='<span aria-hidden="true">↗</span>';
const button=(label,url=wa(),secondary=false)=>`<a class="button${secondary?' secondary':''}" href="${esc(url)}">${label}${arrow}</a>`;
const gallery=(name,caption,cls='')=>`<figure class="${cls}"><a class="photo-open" href="assets/images/${name}.webp" data-caption="${esc(caption)}" aria-label="Открыть фото: ${esc(caption)}">${img(name,caption)}<span class="photo-expand" aria-hidden="true">↗</span></a><figcaption>${caption}</figcaption></figure>`;
const programs=[
 {id:'animator',name:'Любимый герой в гостях',kind:'Аниматор',image:'characters-party',alt:'Лабубу и Куроми на дне рождения в Киндер Пати Дом',price:'3 500 ₽',meta:'60 минут · 1 артист',text:'Игры, танцы и поздравление именинника. Выберите персонажа, которого ребёнок давно мечтает встретить.',label:'Выбрать аниматора'},
 {id:'paper',name:'Бумажное шоу',kind:'Шоу',image:'paper-show',alt:'Дети играют с серебристой бумагой на празднике',price:'7 000 ₽',meta:'60 минут',text:'Танцевальная вечеринка в вихре серебристой бумаги. Когда в веселье хочется включиться и взрослым.',label:'Хочу бумажное шоу'},
 {id:'robots',name:'Встреча с роботами',kind:'Шоу',image:'robots',alt:'Робот Бамблби и супергерои Киндер Пати Дом',price:'6 500 ₽',meta:'60 минут',text:'Большие герои для большого впечатления. Состав выступления и персонажей согласуем перед праздником.',label:'Узнать о роботах'},
 {id:'challenge',name:'«Сможешь Пати»',kind:'Челленджи',image:'teen-party',alt:'Компания подростков на празднике из фотоальбома Киндер Пати Дом',price:'4 500 ₽',meta:'60 минут',text:'Испытания со стаканчиками и шариками: здесь решают ловкость, азарт и поддержка друзей. Для тех, кто уже вырос из сказок.',label:'Обсудить челленджи'},
 {id:'taba',name:'«Таба-Лапка Пати»',kind:'Мастер-класс + вечеринка',image:'taba-workshop',alt:'Блестящая татуировка в виде лапки — дополнение к празднику',price:'По запросу',meta:'5+ · длительность уточняйте',text:'Делаем свой сквиш, пробуем челленджи, танцуем и играем на экране. Маленький сувенир останется на память.',label:'Узнать о Таба-Лапке'},
 {id:'bubbles',name:'Шоу мыльных пузырей',kind:'Шоу',image:'bubble-show',alt:'Артистка проводит интерактивное шоу мыльных пузырей для детей',price:'По запросу',meta:'Состав и длительность согласуем',text:'Пузыри необычных размеров и интерактив с гостями. Красивый момент, который хочется рассматривать и пробовать.',label:'Хочу шоу пузырей'},
 {id:'vr',name:'День рождения в другой реальности',kind:'VR-вечеринка',image:'vr-party',alt:'Участник VR-программы компании в очках виртуальной реальности',price:'По запросу',meta:'Возраст и длительность уточняйте',text:'Для ребят, которым хочется новых впечатлений. Подберём виртуальные приключения и обсудим, как включить VR в праздник вашей компании.',label:'Подобрать VR-программу'}
];
const cards=programs.map(p=>`<article id="${p.id}" class="program${p.id==='vr'?' program-wide':''}"><div class="program-image">${img(p.image,p.alt)}<span class="image-tag">${p.kind}</span>${p.id==='taba'?'<span class="photo-note">На фото — блестящая татуировка</span>':''}</div><div class="program-info"><p class="meta">${p.meta}</p><h3>${p.name}</h3><p>${p.text}</p><div class="program-bottom"><strong>${p.price}</strong><a class="text-link" href="${wa(`Здравствуйте! Интересует программа «${p.name}». Подскажите актуальную стоимость и свободные даты.`)}">${p.label}${arrow}</a></div></div></article>`).join('');
const faqs=[
 ['Можно провести праздник не на вашей площадке?','Да, мы проводим выездные программы дома, на даче, турбазе и других подходящих площадках. Сообщите адрес и формат — обсудим условия и необходимое место.'],
 ['Сколько гостей поместится на площадке?','Пространство на Чапаева, 36 рассчитано на компанию до 40 гостей. При бронировании назовите число детей и взрослых: это поможет согласовать удобный формат праздника.'],
 ['Как выбрать программу по возрасту?','Расскажите, сколько лет имениннику и гостям, что им нравится и насколько активный праздник вы хотите. Поможем выбрать героя или шоу. Возрастные условия VR и отдельных программ уточняются при записи.'],
 ['Как узнать, свободна ли нужная дата?','Напишите в WhatsApp или позвоните: +7 (982) 535-72-37. Назовите дату, удобное время и количество гостей. Менеджер проверит расписание и обсудит с вами бронирование.'],
 ['Что входит в час с аниматором?','Программа с одним артистом длится 60 минут: активные игры, конкурсы, танцевальные флешмобы, реквизит, музыка и аппаратура артиста, элементы аквагрима, мыльные пузыри, вынос торта и фото на ваши устройства.'],
 ['Можно ли принести еду и торт?','Условия стола, еды, напитков и пользования площадкой лучше согласовать при бронировании. Сообщите, что планируете принести и сколько будет гостей: менеджер объяснит подготовку к празднику.']
];
const schema={'@context':'https://schema.org','@graph':[{'@type':'EntertainmentBusiness','@id':base+'#business',name:'Киндер Пати Дом',url:base,telephone:'+79825357237',image:base+'assets/images/family-party.webp',address:{'@type':'PostalAddress',streetAddress:'улица Чапаева, 36',addressLocality:'Нижневартовск',addressCountry:'RU'},openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],opens:'10:00',closes:'21:00'}],sameAs:[vk,'https://2gis.ru/nizhnevartovsk/firm/70000001047353725'],areaServed:{'@type':'City',name:'Нижневартовск'}},{'@type':'FAQPage',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}]};
const html=`<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#faf7f2">
<title>Детские праздники и аниматоры в Нижневартовске — Киндер Пати Дом</title>
<meta name="description" content="День рождения на Чапаева, 36 или с выездом к вам. Аниматоры, бумажное шоу, пузыри, роботы и VR. Киндер Пати Дом, Нижневартовск. Узнайте свободную дату.">
<link rel="canonical" href="${base}"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="icon" href="assets/favicon.png" type="image/png"><link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
<meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="Киндер Пати Дом"><meta property="og:title" content="Киндер Пати Дом — праздник у нас или с выездом к вам"><meta property="og:description" content="Аниматоры, шоу и своё пространство в Нижневартовске. Выберите программу и узнайте свободную дату."><meta property="og:url" content="${base}"><meta property="og:image" content="${base}assets/og-image.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Семейный праздник в Киндер Пати Дом"><meta name="twitter:card" content="summary_large_image">
<link rel="preload" href="assets/fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="assets/styles.css"><script type="application/ld+json">${JSON.stringify(schema)}</script><script src="assets/app.js" defer></script></head>
<body><a class="skip-link" href="#main">К содержанию</a>
<header class="site-header wrap"><a class="brand" href="#" aria-label="Киндер Пати Дом — на главную"><img class="brand-logo" src="assets/images/logo.webp" alt="" width="64" height="44"><span>КИНДЕР<br>ПАТИ ДОМ</span></a><nav aria-label="Основная навигация" id="navigation"><a href="#programs">Программы</a><a href="#venue">Наш дом</a><a href="#gallery">Фото</a><a href="#reviews">Отзывы</a><a href="#contacts">Контакты</a></nav><a class="header-phone" href="tel:+73466257237">+7 (3466) 257-237</a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" aria-label="Открыть меню"><span></span><span></span></button></header>
<main id="main">
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">Нижневартовск · Чапаева, 36</p><h1 id="hero-title">Детские праздники,<br> которые <span>запомнятся</span></h1><p class="hero-description">Аниматоры, шоу и свой дом для праздника в Нижневартовске</p><div class="hero-actions">${button('Узнать свободную дату')}${button('Выбрать программу','#programs',true)}</div><div class="hero-proof"><span>Своя площадка</span><span>До 40 гостей</span><span>Выезд к вам</span></div></div><figure class="hero-photo">${img('hero-paper','Участница праздника Киндер Пати Дом в вихре серебристой бумаги',{hero:true})}<figcaption><span>Вот ради таких моментов</span><span>Бумажное шоу ↗</span></figcaption></figure></section>
<div class="intro-line wrap"><p>Для малышей, школьников<br>и тех, кто уже «почти взрослый».</p><a href="#age">Найдём ваш формат <span aria-hidden="true">↓</span></a></div>
<section id="formats" class="section wrap formats"><div class="section-heading"><div><p class="eyebrow">С чего начнём?</p><h2>У каждого праздника<br>свой характер.</h2></div><p>Можно прийти с готовой идеей.<br>А можно — просто с датой рождения.</p></div><div class="format-links"><a href="#programs">День рождения <span>01 ↗</span></a><a href="#bubbles">Шоу-программа <span>02 ↗</span></a><a href="#animator">Любимый аниматор <span>03 ↗</span></a><a href="#vr">VR-вечеринка <span>04 ↗</span></a><a href="#occasions">Выпускной <span>05 ↗</span></a><a href="#gender">Гендер-пати <span>06 ↗</span></a><a href="#outcall">Праздник с выездом <span>07 ↗</span></a></div></section>
<section id="programs" class="section wrap"><div class="section-heading"><div><p class="eyebrow">Программы и впечатления</p><h2>Что понравится<br>вашему ребёнку?</h2></div><p>От встречи с героем до VR-приключения.<br>Поможем собрать праздник под вашу компанию.</p></div><p class="price-note">Актуальную стоимость и состав программы уточняйте при бронировании.</p><div class="program-grid">${cards}</div></section>
<section class="included section wrap" aria-labelledby="included-title"><div><p class="eyebrow">Просто и понятно</p><h2 id="included-title">Целый час.<br>Один любимый герой.</h2><p>Программа с одним артистом.<br><strong>3 500 ₽ / 60 минут</strong>.</p>${button('Обсудить праздник с аниматором',wa('Здравствуйте! Хочу обсудить программу с одним аниматором на 60 минут.'))}</div><div><h3>Что входит в программу</h3><ul class="included-list"><li>Активные игры и конкурсы</li><li>Танцевальные флешмобы</li><li>Реквизит, музыка и аппаратура артиста</li><li>Элементы аквагрима и мыльные пузыри</li><li>Вынос вашего торта</li><li>Фото на ваши телефоны и камеры</li></ul></div></section>
<section id="venue" class="section venue-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">Наш дом для вашего праздника</p><h2>Приходите в гости.<br>Здесь можно быть детьми.</h2></div><div><p>Своё пространство на Чапаева, 36:<br>игровая зона, герои и место для вашей компании.</p>${button('Посмотреть свободные даты',wa('Здравствуйте! Подскажите свободные даты на площадке Чапаева, 36. Планируем праздник на … гостей.'))}</div></div><div class="venue-facts"><div><strong>40</strong><span>гостей — вместимость пространства</span></div><div><strong>36</strong><span>дом на улице Чапаева</span></div><div><strong>10–21</strong><span>работаем каждый день</span></div></div><div class="venue-gallery">${gallery('party-games','Игры в пространстве Киндер Пати Дом','venue-main')}${gallery('play-zone','Новая игровая зона')}${gallery('party-table','Стол для вашей компании')}${gallery('venue-celebration','Встреча с героями')}${gallery('birthday-table','Гости за праздничным столом')}</div><p class="small muted">Оформление, рассадку и условия пользования площадкой согласуем для вашего праздника.</p></div></section>
<section id="outcall" class="section wrap split-story"><figure>${img('outdoor-party','Артисты Киндер Пати Дом в образах скомороха и Марфуши')}<figcaption>Праздник может приехать к вам</figcaption></figure><div><p class="eyebrow">Собираетесь в другом месте?</p><h2>Тогда мы<br>идём к вам.</h2><p>Дом, квартира, дача, турбаза или ваша площадка — обсудим место и привезём программу. Артист приезжает со своей музыкальной аппаратурой.</p><p>Назовите адрес, возраст детей и число гостей. Проверим, какой формат подойдёт по пространству и условиям.</p>${button('Рассчитать праздник с выездом',wa('Здравствуйте! Нужен праздник с выездом. Адрес: … Дата: … Возраст детей: … Количество гостей: …'))}</div></section>
<section id="age" class="section wrap age-section"><p class="eyebrow">Ориентируемся на интересы</p><h2>Сколько лет<br>вашему имениннику?</h2><p>Выберите возраст — поможем найти программу.<br>Учтём и самого тихого гостя, и самого активного.</p><div class="age-links">${['3–5','5–7','7–10','10+'].map(a=>`<a href="${wa(`Здравствуйте! Помогите подобрать праздник для ребёнка ${a} лет. Дата: … Интересы: …`)}"><strong>${a}</strong><span>лет ${arrow}</span></a>`).join('')}</div></section>
<section id="characters" class="section wrap"><div class="section-heading"><div><p class="eyebrow">Тот самый персонаж</p><h2>«Он правда<br>придёт ко мне?»</h2></div><div><p>Любимые герои выходят из экрана.<br>Наличие костюма на дату уточняйте у менеджера.</p><a class="text-link" href="${wa('Здравствуйте! Пришлите, пожалуйста, актуальный список всех персонажей для праздника.')}">Узнать всех персонажей ${arrow}</a></div></div><div class="characters-grid">${[['labubu','Лабубу'],['kuromi','Куроми'],['harry','Гарри Поттер'],['panda','Панда'],['bunny','Зайка'],['elsa','Эльза']].map(([n,c])=>gallery(n,c)).join('')}</div><p class="character-more">Ещё в программах: Леон / Brawl Stars, Пикачу, Хаги Ваги, Машенька, Алёнка, Ариэль, Соник, Уэнсдей, Лалафанфан и другие герои. <a href="${wa('Здравствуйте! Интересует Леон / Brawl Stars. Уточните стоимость программы и свободную дату.')}">Леон: 3 500 ₽ / 60 минут ↗</a></p></section>
<section class="section wrap extras"><div class="section-heading"><div><p class="eyebrow">Ещё немного праздника</p><h2>Добавьте своё<br>«а давайте ещё!»</h2></div><p>Мастер-класс, аквагрим или пиньята —<br>выберите дополнение к вашей программе.</p></div><div class="extras-list">${[['Готовая пиньята','1 200–1 500 ₽'],['Дымовое шоу','500 ₽'],['Мастер-класс «Слайм»','350 ₽ / ребёнок'],['Аквагрим','250 ₽ / ребёнок'],['Блестящие татуировки','По запросу'],['Другие мастер-классы','По запросу']].map(([n,p])=>`<a href="${wa(`Здравствуйте! Хочу добавить к празднику: ${n}. Подскажите стоимость и условия.`)}"><span>${n}</span><strong>${p}</strong><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section id="occasions" class="section wrap occasion-grid"><div class="occasion-photo">${img('graduation','Команда артистов Киндер Пати Дом готова к выпускным праздникам')}</div><div><p class="eyebrow">Поводов встретиться больше</p><h2>Выпускной.<br>Новый год.<br>Новая история.</h2><p>Последний звонок в садике, выпускной класса, окончание четверти, сезонная вечеринка или встреча с Дедом Морозом и Снегурочкой. Обсудим программу для вашей группы.</p><a class="text-link" href="${wa('Здравствуйте! Хотим организовать выпускной или сезонный праздник для группы. Подскажите варианты.')}">Подобрать групповой праздник ${arrow}</a><div id="gender" class="gender"><h3>А может, гендер-пати?</h3><p>Встретьте большую новость вместе с близкими.<br><strong>5 000 ₽ / 60 минут.</strong></p><a class="text-link" href="${wa('Здравствуйте! Интересует гендер-пати. Подскажите актуальную стоимость и варианты программы.')}">Обсудить гендер-пати ${arrow}</a></div></div></section>
<section id="gallery" class="section wrap"><div class="section-heading"><div><p class="eyebrow">Наш фотоальбом</p><h2>Праздник закончится.<br>А это останется.</h2></div><p>Нажмите на фото, чтобы рассмотреть поближе.</p></div><div class="album">${gallery('family-party','День рождения в кругу семьи и друзей','album-wide')}${gallery('birthday-friends','Праздник с Лабубу и Куроми')}${gallery('bubble-ring','Большие мыльные пузыри')}${gallery('birthday-table','Герой рядом с именинницей')}${gallery('paper-dance','В самом центре бумажного шоу','album-wide')}${gallery('friends','Когда все друзья рядом')}</div><a class="text-link gallery-vk" href="${vk}">Больше праздников в VK ${arrow}</a></section>
<section id="reviews" class="section reviews-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">После праздника</p><h2>Родители —<br>о своих впечатлениях.</h2></div><div><p>Больше впечатлений и историй — в отзывах на 2ГИС.</p><a class="text-link" href="${reviews}">Все отзывы в 2ГИС ${arrow}</a></div></div><div class="reviews-grid">${[
 ['Наталья Шиманова','Очень веселые аниматоры','О взаимодействии артистов с детьми и взрослыми.'],
 ['Ксения Федько','само пространство очень уютное!','О новогоднем празднике для первоклассников.'],
 ['Анастасия Бунина','Сюрприз удался на 100%.','Об экспресс-поздравлении с Дэдпулом.'],
 ['Нина Зайцева','Гости и именинница остались в восторге','О дне рождения племянницы.']
 ].map(([name,quote,context])=>`<figure class="review"><span class="review-source">2ГИС · отзыв о компании</span><blockquote>«${quote}»</blockquote><p>${context}</p><figcaption><strong>${name}</strong><a href="${reviews}" aria-label="Читать отзыв: ${name}">Читать в 2ГИС ↗</a></figcaption></figure>`).join('')}</div></div></section>
<section class="section wrap city-section"><figure>${img('city-archive','Артисты Киндер Пати на городской праздничной площадке')}<figcaption>Городской праздник · архив, 2024</figcaption></figure><div><p class="eyebrow">Часть городского праздника</p><h2>Встречаемся<br>и за пределами дома.</h2><p>Детские программы на «Самотлорских ночах — 2026» и интерактивные площадки на фестивале «Открытая сцена — 2025».</p><div class="source-links"><a href="https://samotlorfest.ru/program">Программа «Самотлорских ночей» ↗</a><a href="https://dantser.ru/фестиваль-открытая-сцена/">Анонс «Открытой сцены» ↗</a></div></div></section>
<section class="section wrap steps-section"><div class="section-heading"><div><p class="eyebrow">От идеи до встречи</p><h2>Ваш план —<br>всего четыре шага.</h2></div></div><ol class="steps"><li><span>01</span><h3>Напишите или позвоните</h3><p>Начать можно с простого «хотим праздник».</p></li><li><span>02</span><h3>Расскажите о ребёнке</h3><p>Дата, возраст, интересы и количество гостей.</p></li><li><span>03</span><h3>Выберите программу</h3><p>Вместе подберём героя, шоу и площадку.</p></li><li><span>04</span><h3>Согласуйте детали</h3><p>Подтвердим время, стоимость и условия бронирования.</p></li></ol></section>
<section class="section wrap faq-section"><div><p class="eyebrow">Родители спрашивают</p><h2>Хорошие вопросы.<br>Понятные ответы.</h2><p>Остался свой?<br><a class="text-link" href="${wa('Здравствуйте! Есть вопрос о проведении праздника.')}">Задайте его нам ${arrow}</a></p></div><div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>
<section id="contacts" class="contacts-section"><div class="wrap contacts-inner"><div><p class="eyebrow">Киндер Пати Дом · Нижневартовск</p><h2>Давайте придумаем<br>ваш праздник.</h2><p>Вы расскажете о ребёнке.<br>Мы поможем с остальным.</p>${button('Узнать свободную дату в WhatsApp')}<p class="small">Откроется чат с подготовленным сообщением.<br>Дату и детали подтвердит менеджер.</p></div><div class="contact-details"><a class="contact-phone" href="tel:+79825357237">+7 (982) 535-72-37</a><a href="tel:+73466257237">+7 (3466) 257-237</a><div><h3>Ждём вас здесь</h3><address>Нижневартовск, ул. Чапаева, 36</address><p>Каждый день, 10:00–21:00</p><a class="text-link" href="https://2gis.ru/nizhnevartovsk/firm/70000001047353725">Открыть в 2ГИС ${arrow}</a></div><a class="text-link" href="${vk}">Программы и новости в VK ${arrow}</a></div></div></section>
</main><footer class="wrap footer"><a class="brand" href="#"><img class="brand-logo" src="assets/images/logo.webp" alt="" width="64" height="44"><span>КИНДЕР<br>ПАТИ ДОМ</span></a><p>Детские праздники в Нижневартовске.<br>© 2026 Киндер Пати Дом</p><p class="small">Информация о ценах не является публичной офертой.</p><a href="#main" class="back-top" aria-label="Вернуться наверх">↑</a></footer>
<div class="mobile-bar"><a href="${wa()}" class="button">Узнать свободную дату ${arrow}</a><a href="tel:+79825357237" class="mobile-call" aria-label="Позвонить в Киндер Пати Дом"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m7 3 3 5-2 2c1 3 3 5 6 6l2-2 5 3c0 3-2 5-5 4C9 19 5 15 3 8 2 5 4 3 7 3Z"/></svg></a></div>
<dialog id="lightbox" aria-label="Фотогалерея"><div class="lightbox-toolbar"><span id="photo-count" aria-live="polite"></span><button class="lightbox-close" aria-label="Закрыть фото">Закрыть ×</button></div><div class="lightbox-stage"><button class="photo-prev" aria-label="Предыдущее фото">←</button><img id="lightbox-image" alt=""><button class="photo-next" aria-label="Следующее фото">→</button></div><p id="lightbox-caption" aria-live="polite"></p></dialog>
</body></html>`;
fs.writeFileSync('index.html',html);
fs.mkdirSync('dist',{recursive:true});
for(const file of ['index.html','robots.txt','sitemap.xml','.nojekyll','404.html']){if(fs.existsSync(file))fs.copyFileSync(file,path.join('dist',file));}
fs.cpSync('assets','dist/assets',{recursive:true});
console.log('Built static page:',programs.length,'programs;',media.length,'photographic assets.');
